### ISSUE TITLE
Add a more appropriate license

### ISSUE THREAD

**Issue by Hoboneer** [MaxwellSalmon/DUGA#10]
Hey again, so I've noticed that the license you chose for your code is Creative Commons.

I've read that the license chosen for this game isn't appropriate for software; see https://github.com/github/choosealicense.com/issues/33#issuecomment-21006341.

So would you change the license to something more appropriate for software and then add a license separately for the non-software parts (e.g. the assets)?

https://choosealicense.com is a good site to get some ideas.

**Comment by MaxwellSalmon** [comment]
I have updated the license to Mozilla Public License 2.0

I think that will do :-)
