### ISSUE TITLE
Crash in the tutorial when managing weapons

### ISSUE THREAD

**Issue by Makoren** [MaxwellSalmon/DUGA#12]
CrashReport.log: https://pastebin.com/bh59G7Nd

After starting the game, immediately go to the tutorial before doing anything else. When you reach the gauss rifle, swap the rifle with your primary weapon, then walk over to the weapon that was dropped, and drop the pistol. This seems to crash the game every time with the same log. I picked up all the weapons and ammo in the previous rooms prior to this.

The problem appears to be a slot in the inventory not being assigned anything before being used.

**Comment by MaxwellSalmon** [comment]
Thank you! I have fixed the issue :-)
