### ISSUE TITLE
DUGA-Launcher.app doesn't open on macOS

### ISSUE THREAD

**Issue by AokiAhishatsu** [MaxwellSalmon/DUGA#13]
I followed the download and install instructions on the website and after clicking open I just get [this error](https://i.imgur.com/3GeMCx0.png).

macOS 10.14.1

**Comment by MaxwellSalmon** [comment]
Unfortunately, I cannot help you with the macOS version, as I am not the one who compiled it. I have no idea how it works. I am sorry. Try in the forum om itch.io, where the version was created.
