### ISSUE TITLE
[Idea] Simplified weapon system

### ISSUE THREAD

**Issue by Nexuzzzz** [MaxwellSalmon/DUGA#17]
I took a look at the source code, and adding new weapons seems like a hassle, since you need to define them in the `load_guns()` function and in `load_item_types()`. Wouldn't it be easier if you'd store all information needed in a json file (minus the graphical items ofcourse)? This could make it really easy to add new weapons

**Comment by Nexuzzzz** [comment]
also, what program did you use to create the pixel art, or where did you get them from?

**Comment by Nexuzzzz** [comment]
Currently working on a fork of DUGA, i'll be working on restructuring all the code and optimizing some stuff. I'll also add some new configuration options and look into the new weapon system

**Comment by MaxwellSalmon** [comment]
You are welcome to alter as much code as you want. I agree, that it is bothersome to work with at the moment. 
I used Aseprite for most of the graphics, I really recommend it.

**Comment by Nexuzzzz** [comment]
sadly i had some issues with my drive, and it passed away. I'll be a bit busy for a while because i'll be reconfiguring my system. I'll let ya know once i get back to the code

**Comment by MaxwellSalmon** [comment]
Feel free to do so - but just a heads up. I am no longer developing this game, so I do not plan on accepting pull requests beyond simple bug fixes. However you are more than welcome to implement it in your own fork and I'll take a look.

**Comment by Nexuzzzz** [comment]
alright, i was on vacation for a while so i didn't do much. So far i've restructured the entire code, cleaned up the syntax, and removed some unneeded stuff too
