### ISSUE TITLE
Failed to create renderer

### ISSUE THREAD

**Issue by SentienceinTech** [MaxwellSalmon/DUGA#18]
' gameCanvas = Canvas(SETTINGS.canvas_map_width, SETTINGS.canvas_map_height)
  File "C:\Users\Keegan Marsh\Downloads\DUGA-master\DUGA-master\MAIN.py", line 175, in __init__
    self.window = pygame.display.set_mode((self.width, int(self.height+(self.height*0.15))), pygame.HWSURFACE + pygame.SCALED + pygame.NOFRAME + pygame.FULLSCREEN, 32, vsync=1)
pygame.error: failed to create renderer'
How do I fix this?

**Comment by MaxwellSalmon** [comment]
Hello, this may be a Pygame issue. 

What version of Python and Pygame are you running and does the following code produce an error for you?

`>>> import pygame`
`>>>pygame.init()`
