### ISSUE TITLE
Add tags for stable-ish versions

### ISSUE THREAD

**Issue by Hoboneer** [MaxwellSalmon/DUGA#9]
Hey, I've been going through your work on this, and it's pretty sweet-- nice work!

I've noticed that there's no tags for stable versions (like the versions in the tech demos), meaning that I'm unable to test the engine and play around with it at those points in time.

**Comment by MaxwellSalmon** [comment]
Thanks a lot for your feedback! 

I never really thought anyone would use it besides me, so I didn't take it into account. At the moment the game will probably not run, but I believe it works around the commit, 

https://github.com/MaxwellSalmon/DUGA/tree/32c63c708a488b3c697339ec36dbe841a4a8ad86

But to be honest, I am not completely sure. I know, that the version I had when releasing a playable tech demo is stable - if you are interested, I can send it to you.

**Comment by MaxwellSalmon** [comment]
If you are interested, I have made the most recent version stable.

https://github.com/MaxwellSalmon/DUGA/commit/88c6a0564ffa744ea7d03f3709b759c11b318f25

I looks forward to see, if you find anything interesting!
